# Generated by Django 4.2.1 on 2024-03-02 08:30

from django.db import migrations, models
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_folder',
            field=models.FileField(upload_to=projects.models.project_folder_upload_path),
        ),
    ]
