# Generated by Django 4.2.1 on 2024-03-02 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_project_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_tech_stack',
            field=models.TextField(default='Python'),
        ),
    ]
