# Generated by Django 4.2.1 on 2024-03-01 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
